### ISSUE TITLE
Cannot set the template filename when using the buf remote plugin

### ISSUE THREAD

**Issue by ZeeD** [pseudomuto/protoc-gen-doc#513]
I use `buf` with your plugin to generate documentation.
In the `buf.gen.yaml` I've set `opt: 'markdown.tmpl,doc.md'` to use a custom template.

Using a local copy of your plugin (obtained via `go get`) I can generate the documentation succesfully.

I saw that it's possible to use [remote plugins with buf](https://buf.build/community/pseudomuto-doc), but with this version it seems I cannot set the template name, and I got the error:
`Failure: plugin "buf.build/community/pseudomuto-doc:v1.5.1" exited with non-zero status 1: 2023/03/29 09:06:28 open markdown.tmpl: no such file or directory`

This is my "new" `buf.gen.yaml` (the commented out lines were present in the working configuration):
```yaml
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/community/pseudomuto-doc
#  - name: doc
#    path: bin/protoc-gen-doc
    out: docs
    opt: 'markdown.tmpl,doc.md'
```

I've tried to set also an absolute path, or different relative paths... but it seems it is not recognized.

**Comment by amenzhinsky** [comment]
@ZeeD the trick is remote plugins work a bit differently as you might expect, `buf generate` doesn't download and call `protoc-gen-doc`, instead it sends proto file contents along with opts to `buf.build` and receives the output from the server.

**Comment by ZeeD** [comment]
uhm... 
apart from the "security" implications (a schema is not exactly PII, but I'm not sure I can share it outside my job without approval)
then is there a way to tell buf to _also_ upload some additional files (like my `markdown.tmpl`)?
Is this something related directly to your project or is this something I need to address with `buf` developers?

**Comment by ZeeD** [comment]
closing as this is not a protoc-gen-doc issue

**Comment by nacx** [comment]
For those like me coming to this now, a trivial workaround is to use it as a local plugin as follows:
```yaml
  - local: ["go", "run", "github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@v1.5.1"]
    strategy: all
    out: docs
    opt: markdown.tmpl,doc.md
```
